import { PaymentAddressNative } from './wasm/glue';
import { Hash, ShortHash } from './Hash';
import { Script } from './Script';
export declare class PaymentAddress {
    private addressStr;
    private tokenAware;
    private legacy;
    static mainnetP2kh: number;
    static mainnetP2sh: number;
    static testnetP2kh: number;
    static testnetP2sh: number;
    static fromNative(native: PaymentAddressNative, destroy?: boolean): PaymentAddress;
    static fromHash(hash: Hash, version: number): PaymentAddress;
    static fromShortHash(hash: ShortHash, version: number): PaymentAddress;
    static fromString(addressStr: string): PaymentAddress | undefined;
    static isValid(addressStr: string): boolean;
    constructor(addressStr: string, tokenAware?: boolean, legacy?: boolean);
    static fromScript(script: Script, version: number): PaymentAddress;
    static fromPayPublicKeyHashScript(script: Script, version: number): PaymentAddress;
    toNative(): PaymentAddressNative;
    get hash20(): ShortHash;
    get hash32(): Hash;
    get hash(): ShortHash;
    get version(): number;
    encoded(): string;
    encodedCashAddr(): string;
    encodedCashTokens(): string;
    encodedLegacy(): string;
    static extract(script: Script, p2khVersion: number, p2shVersion: number): PaymentAddress[];
    static extractInput(script: Script, p2khVersion: number, p2shVersion: number): PaymentAddress[];
    static extractOutput(script: Script, p2khVersion: number, p2shVersion: number): PaymentAddress[];
}
export default PaymentAddress;
