export declare class RuleFork {
    static forkMinYear: number;
    static forkMaxYear: number;
    static noRules: number;
    static easyBlocks: number;
    static bip16Rule: number;
    static bip30Rule: number;
    static bip34Rule: number;
    static bip66Rule: number;
    static bip65Rule: number;
    static bip90Rule: number;
    static allowCollisions: number;
    static bip68Rule: number;
    static bip112Rule: number;
    static bip113Rule: number;
    static bchUahf: number;
    static bchDaaCw144: number;
    static bchPythagoras: number;
    static bchEuclid: number;
    static bchPisano: number;
    static bchMersenne: number;
    static bchFermat: number;
    static bchEuler: number;
    static bchGauss: number;
    static bchDescartes: number;
    static bchLobachevski: number;
    static bchGalois: number;
    static bchLeibniz: number;
    static retarget: number;
    static unverified: number;
    static bip34Activations: number;
    static allRules: number;
    static baseForks(easyBlocks?: boolean): number;
    static allForks(easyBlocks?: boolean): number;
    static enabledForksByDate(year: number, month: number, easyBlocks?: boolean): number;
    static enabledForksByYear(year: number, easyBlocks?: boolean): number;
}
export default RuleFork;
